### ISSUE TITLE
Error when sending pictures

### ISSUE THREAD

**Issue by quimey** [eisenjulian/trading-card-exchange#2]
Sending pictures when there's no conversation going on causes error:
```
2018-07-22T14:56:38.001531+00:00 app[web.1]: [u'56', u'TOM JORDAN', u'']
2018-07-22T14:56:38.001757+00:00 app[web.1]: 2018-07-22 14:56:38.001636: Found match tom jordan in Morocco Tom Jordan
2018-07-22T14:56:38.007125+00:00 app[web.1]: 2018-07-22 14:56:38.006784: sending message to 1664422086988784: null
2018-07-22T14:56:38.007628+00:00 app[web.1]: 2018-07-22 14:56:38.007546: Traceback (most recent call last):
2018-07-22T14:56:38.007631+00:00 app[web.1]:   File "/app/src/connectors/messenger.py", line 46, in webhook
2018-07-22T14:56:38.007633+00:00 app[web.1]:     messenger_sender.send_messages(messaging_event['sender'], messages)
2018-07-22T14:56:38.007635+00:00 app[web.1]:   File "/app/src/connectors/messenger_sender.py", line 26, in send_messages
2018-07-22T14:56:38.007637+00:00 app[web.1]:     for message in messages:
2018-07-22T14:56:38.007639+00:00 app[web.1]: TypeError: 'NoneType' object is not iterable
2018-07-22T14:56:38.008028+00:00 app[web.1]: 
```

**Comment by eisenjulian** [comment]
Voy a hacer que te tire un boton si la queres agregar a cual de las dos listas, te parece?

**Comment by quimey** [comment]
Dale, o aunque sea que te tire info de la figurita
