### ISSUE TITLE
Error in dialog manager

### ISSUE THREAD

**Issue by quimey** [eisenjulian/trading-card-exchange#3]
Caused by clicking one of the quick action buttons when bot expecting for message

2018-07-24T11:16:09.530372+00:00 app[web.1]: 2018-07-24 11:16:09.530062: {"object": "page", "entry": [{"messaging": [{"postback": {"payload": "{\"intent\": \"trades\"}", "title": "My trades"}, "sender": {"id": "1664422086988784"}, "timestamp": 1532430969451, "recipient": {"id": "199387144081747"}}], "time": 1532430969451, "id": "199387144081747"}]}
2018-07-24T11:16:09.742086+00:00 app[web.1]: 2018-07-24 11:16:09.741973: Traceback (most recent call last):
2018-07-24T11:16:09.530372+00:00 app[web.1]: 2018-07-24 11:16:09.530062: {"object": "page", "entry": [{"messaging": [{"postback": {"payload": "{\"intent\": \"trades\"}", "title": "My trades"}, "sender": {"id": "1664422086988784"}, "timestamp": 1532430969451, "recipient": {"id": "199387144081747"}}], "time": 1532430969451, "id": "199387144081747"}]}
2018-07-24T11:16:09.742086+00:00 app[web.1]: 2018-07-24 11:16:09.741973: Traceback (most recent call last):
2018-07-24T11:16:09.742089+00:00 app[web.1]:   File "/app/src/connectors/messenger.py", line 45, in webhook
2018-07-24T11:16:09.742091+00:00 app[web.1]:     messages = dialog_manager.run(messaging_event)
2018-07-24T11:16:09.742093+00:00 app[web.1]:   File "/app/src/dialog_manager.py", line 63, in run
2018-07-24T11:16:09.742095+00:00 app[web.1]:     messages = process(messaging_event)
2018-07-24T11:16:09.742097+00:00 app[web.1]:   File "/app/src/dialog_manager.py", line 107, in process
2018-07-24T11:16:09.742099+00:00 app[web.1]:     ] for user in users}
2018-07-24T11:16:09.742101+00:00 app[web.1]:   File "/app/src/dialog_manager.py", line 107, in <dictcomp>
2018-07-24T11:16:09.742102+00:00 app[web.1]:     ] for user in users}
2018-07-24T11:16:09.742104+00:00 app[web.1]: KeyError: 'text'
2018-07-24T11:16:09.742089+00:00 app[web.1]:   File "/app/src/connectors/messenger.py", line 45, in webhook
2018-07-24T11:16:09.742091+00:00 app[web.1]:     messages = dialog_manager.run(messaging_event)
2018-07-24T11:16:09.742093+00:00 app[web.1]:   File "/app/src/dialog_manager.py", line 63, in run
2018-07-24T11:16:09.742095+00:00 app[web.1]:     messages = process(messaging_event)
2018-07-24T11:16:09.742097+00:00 app[web.1]:   File "/app/src/dialog_manager.py", line 107, in process
2018-07-24T11:16:09.742099+00:00 app[web.1]:     ] for user in users}
2018-07-24T11:16:09.742101+00:00 app[web.1]:   File "/app/src/dialog_manager.py", line 107, in <dictcomp>
2018-07-24T11:16:09.742102+00:00 app[web.1]:     ] for user in users}
2018-07-24T11:16:09.742104+00:00 app[web.1]: KeyError: 'text'

**Comment by eisenjulian** [comment]
Fixed
